
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDg3ZTIzZDdkZmY1MDAyZDBmMzUyZGEiLCJpYXQiOjE2MTk1MTkzMzB9.hvqBDma0Sr1WQbI14UG1xAY9qd2onTLbosAb1_VLKgc

POST http://insta-stories.herokuapp.com/signup HTTP/1.1
   content-type: application/json

{
    "name": "test",
    "email": "test1@gmail.com",
    "password": "1234"
}

###

POST http://localhost:4000/signup HTTP/1.1
   content-type: application/json

{
    "name": "test2",
    "email": "test11@gmail.com",
    "password": "1234"
}

###

POST http://localhost:8080/signin
   content-type: application/json

{
    "email": "send1@gmail.com",
    "password": "ashishthakur"
}

###
GET http://localhost:8080/protected 
   content-type: application/json
   Authorization: Bearer{{token}}

###

POST http://localhost:8080/creatstories
   Content-Type: application/json
   Authorization: Bearer{{token}}

{
    "title": "test title",
    "body": "ashishthakur"
}

###

POST http://localhost:4000/postwork
   Content-Type: application/json

{
   "title": "test title2",
   "description": "ashishthakur2",
   "category":"work categoty2",
   "vaccinated":"yes",
   "amount":"10rs"
   
}

###

POST https://insta-stories.herokuapp.com/postwork
   Content-Type: application/json

{
   "title": "lappy",
   "description": "hi i want to install window xp  in my pc",
   "category":"Tech",
   "vaccinated":"yes",
   "amount":"300rs"
} 


###

GET https://insta-stories.herokuapp.com/allwork HTTP/1.1


###

GET http://localhost:8080/mystories HTTP/1.1
Content-Type: application/json
Authorization: Bearer{{token}}